# Natural Language Processing + Decision Science

👩🏻‍🏫 In this challenge, we will combine:
* 🗣 Natural Language Processing
* 📊 Decision Science

🎯 The goal is to understand the **negative (bad) reviews** of products and sellers on Olist.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Data Manipulation
import numpy as np
import pandas as pd
pd.set_option("display.max_columns",None)

# Machine Learning
from sklearn.pipeline import make_pipeline

# Language Processing
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
import string
import unidecode as unidecode

# Vectorizers and NLP Models
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

🕵🏻‍♂️ Imagine that Olist CEO [Tiago Dalvi](https://www.linkedin.com/in/tiagodalvi/) asks you to read and understand the reviews.

- What did customers say when they rated their orders **1**, **2**, or **3** stars?
- What are the most common negative reviews?
    - About the worst-rated products?
    - About the worst-rated sellers?

## (0) Setup 🔨

First, we will load the DataFrame containing all information related to Olist reviews!

In [3]:
df = pd.read_csv("https://d32aokrjazspmn.cloudfront.net/materials/olist_reviews.csv")

In [4]:
df.head()

,review_id,length_review,review_score,order_id,product_category_name,full_review
0,e64fb393e7b32834bb789ff8bb30750e,37,5,658677c97b385a9be170737859d3511b,ferramentas_jardim,Recebi bem antes do prazo estipulado.
1,f7c4243c7fe1938f181bec41a392bdeb,100,5,8e6bfb81e283fa7e4f11123a3fb894f1,esporte_lazer,Parabéns lojas lannister adorei comprar pela ...
2,8670d52e15e00043ae7de4c01cc2fe06,174,4,b9bf720beb4ab3728760088589c62129,eletroportateis,recomendo aparelho eficiente. no site a marca ...
3,4b49719c8a200003f700d3d986ea1a19,45,4,9d6f15f95d01e79bd1349cc208361f09,beleza_saude,"Mas um pouco ,travando...pelo valor ta Boa.\r\n"
4,3948b09f7c818e2d86c9a546758b2335,56,5,e51478e7e277a83743b6f9991dbfa3fb,informatica_acessorios,"Super recomendo Vendedor confiável, produto ok..."

In [5]:
df.shape

(36148, 6)

## (2) Text Cleaning

🧹 Create a `cleaning(sentence)` function and apply it to the reviews. **Note that there is no Portuguese lemmatizer in NLTK** (usually there is not, but there is the `nltk.stem.RSLPStemmer` stemmer).

In [7]:
nltk.download('rslp')

[nltk_data] Downloading package rslp to /Users/yaren/nltk_data...
[nltk_data]   Unzipping stemmers/rslp.zip.

True

In [8]:
def cleaning(sentence):
    sentence = sentence.strip()
    sentence = sentence.lower()
    sentence = "".join(char for char in sentence if not char.isdigit())

    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, "") # remove punctuation
    
    tokenized_sentence = word_tokenize(sentence)
    stop_words = set(stopwords.words("portuguese")) # define stop words
    tokenized_sentence_cleaned = [word for word in tokenized_sentence if word not in stop_words] # remove stop words

    lemmatizer = nltk.stem.RSLPStemmer()
    tokenized_sentence_stemmed = [lemmatizer.stem(word) for word in tokenized_sentence_cleaned]

    return " ".join(tokenized_sentence_stemmed)

df["full_review_cleaned"] = df["full_review"].apply(cleaning)

In [9]:
df.head()

,review_id,length_review,review_score,order_id,product_category_name,full_review,full_review_cleaned
0,e64fb393e7b32834bb789ff8bb30750e,37,5,658677c97b385a9be170737859d3511b,ferramentas_jardim,Recebi bem antes do prazo estipulado.,receb bem ant praz estipul
1,f7c4243c7fe1938f181bec41a392bdeb,100,5,8e6bfb81e283fa7e4f11123a3fb894f1,esporte_lazer,Parabéns lojas lannister adorei comprar pela ...,parabém loj lannist ador compr internet segur ...
2,8670d52e15e00043ae7de4c01cc2fe06,174,4,b9bf720beb4ab3728760088589c62129,eletroportateis,recomendo aparelho eficiente. no site a marca ...,recom aparelh efici sit marc aparelh impress d...
3,4b49719c8a200003f700d3d986ea1a19,45,4,9d6f15f95d01e79bd1349cc208361f09,beleza_saude,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",pouc travandopel val ta boa
4,3948b09f7c818e2d86c9a546758b2335,56,5,e51478e7e277a83743b6f9991dbfa3fb,informatica_acessorios,"Super recomendo Vendedor confiável, produto ok...",sup recom vend confi produt ok entreg ant praz

## (3) Analysis of Bad Reviews

### (3.1) Dataset with low review scores

😱 What proportion of reviews received a score between 1 and 3?

In [13]:
bad_reviews_ratio = (df.review_score < 4).sum() / len(df)
print(f"{bad_reviews_ratio:.1%} of reviews have a score of 1, 2, or 3")

26.7% of reviews have a score of 1, 2, or 3

🕵🏻‍♂️ Let us focus on these reviews...

In [14]:
df[df.review_score < 4].head()

,review_id,length_review,review_score,order_id,product_category_name,full_review,full_review_cleaned
14,e233e51d11511bf30e568c76360ace52,97,1,548df2c6e5f089574614894bca78acf5,eletronicos,recebi somente 1 controle Midea Split ESTILO....,receb soment control mide split estil falt con...
23,8b230a1373c6dc4bd867099fda1d7039,60,3,071251fe3b3493294536f03737a8a679,ferramentas_jardim,Eu comprei duas unidades e só recebi uma e ag...,compr dua unidad receb agor faç
24,cb2fc3e5711b5ae85e0491ee18af63ed,72,3,34e6d418f368f8079ae152bc178bc66a,beleza_saude,"Produto bom, porém o que veio para mim não co...",produt bom porém vei mim condiz fot anúnci
25,60c714ed14cef913944a3147094a4742,36,1,9ac05114800f02bfaa783bd76842dbe2,moveis_decoracao,"Produto muito inferior, mal acabado.",produt inferi mal acab
28,0bd4dcc4f6c4621baf37f73495cad8c4,16,3,a11cd01ac67beef7e8bf09740d8a35c1,esporte_lazer,Entrega no prazo,entreg praz

### (3.2) Vectorization

🔡 ➡️ 🔢 Vectorize your texts.

- Make sure to account for **bigrams** (two-word expressions).
- Set `max_df = 0.75` to remove overly frequent words.
- Spoiler: you will end up with **20,000+** words…  
  For this challenge, limit to only `max_features = 5000`.

In [17]:
bad_reviews_df = df[df.review_score < 4]

vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_df=0.75, max_features=5000)

vectorized_reviews = vectorizer.fit_transform(bad_reviews_df["full_review_cleaned"])
vectorized_reviews = pd.DataFrame(
    vectorized_reviews.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=bad_reviews_df.index
)

vectorized_reviews.head()

    abaix  abert  aborrec  abr  abr caix  abr cham  abr embal  abr fech  \
14    0.0    0.0      0.0  0.0       0.0       0.0        0.0       0.0
23    0.0    0.0      0.0  0.0       0.0       0.0        0.0       0.0
24    0.0    0.0      0.0  0.0       0.0       0.0        0.0       0.0
25    0.0    0.0      0.0  0.0       0.0       0.0        0.0       0.0
28    0.0    0.0      0.0  0.0       0.0       0.0        0.0       0.0

    abr reclam  abril  absurd  absurd entreg      acab  acab compr  acab deix  \
14         0.0    0.0     0.0            0.0  0.000000         0.0        0.0
23         0.0    0.0     0.0            0.0  0.000000         0.0        0.0
24         0.0    0.0     0.0            0.0  0.000000         0.0        0.0
25         0.0    0.0     0.0            0.0  0.374942         0.0        0.0
28         0.0    0.0     0.0            0.0  0.000000         0.0        0.0

    acab fic  acab produt  acab receb  acab ruim  aceit  acend  acert  acess  \
14       0.0          0.0         0.0        0.0    0.0    0.0    0.0    0.0
23       0.0          0.0         0.0        0.0    0.0    0.0    0.0    0.0
24       0.0          0.0         0.0        0.0    0.0    0.0    0.0    0.0
25       0.0          0.0         0.0        0.0    0.0    0.0    0.0    0.0
28       0.0          0.0         0.0        0.0    0.0    0.0    0.0    0.0

    acessóri  ach  ach absurd  ach bem  ach car  ach cord  ach demor  ach dev  \
14       0.0  0.0         0.0      0.0      0.0       0.0        0.0      0.0
23       0.0  0.0         0.0      0.0      0.0       0.0        0.0      0.0
24       0.0  0.0         0.0      0.0      0.0       0.0        0.0      0.0
25       0.0  0.0         0.0      0.0      0.0       0.0        0.0      0.0
28       0.0  0.0         0.0      0.0      0.0       0.0        0.0      0.0

    ach entreg  ach estranh  ach fornec  ach fret  ach loj  ach mant  \
14         0.0          0.0         0.0       0.0      0.0       0.0
23         0.0          0.0         0.0       0.0      0.0       0.0
24         0.0          0.0         0.0       0.0      0.0       0.0
25         0.0          0.0         0.0       0.0      0.0       0.0
28         0.0          0.0         0.0       0.0      0.0       0.0

    ach mater  ach melhor  ach pequen  ach pouc  ach praz  ach produt  \
14        0.0         0.0         0.0       0.0       0.0         0.0
23        0.0         0.0         0.0       0.0       0.0         0.0
24        0.0         0.0         0.0       0.0       0.0         0.0
25        0.0         0.0         0.0       0.0       0.0         0.0
28        0.0         0.0         0.0       0.0       0.0         0.0

    ach péss  ach qual  ach vei  acid  acim  acion  acompanh  acompanh ped  \
14       0.0       0.0      0.0   0.0   0.0    0.0       0.0           0.0
23       0.0       0.0      0.0   0.0   0.0    0.0       0.0           0.0
24       0.0       0.0      0.0   0.0   0.0    0.0       0.0           0.0
25       0.0       0.0      0.0   0.0   0.0    0.0       0.0           0.0
28       0.0       0.0      0.0   0.0   0.0    0.0       0.0           0.0

    acompanh produt  acondicion  acontec  acontec compr  acontec produt  \
14              0.0         0.0      0.0            0.0             0.0
23              0.0         0.0      0.0            0.0             0.0
24              0.0         0.0      0.0            0.0             0.0
25              0.0         0.0      0.0            0.0             0.0
28              0.0         0.0      0.0            0.0             0.0

    acord  acord descr  acostum  acostum compr  acredit  acríl  acríl fic  \
14    0.0          0.0      0.0            0.0      0.0    0.0        0.0
23    0.0          0.0      0.0            0.0      0.0    0.0        0.0
24    0.0          0.0      0.0            0.0      0.0    0.0        0.0
25    0.0          0.0      0.0            0.0      0.0    0.0        0.0
28    0.0          0.0      0.0            0.0      0.0    0.0        0.0

    acus  adapt  adequ  adequad  ader  ades  ades mal  ades pared  ades pra  \
14   0.0    0.0    0.0      0.0   0.0   0.0       0.0         0.0       0.0
23   0.0    0.0    0.0      0.0   0.0   0.0       0.0         0.0       0.0
24   0.0    0.0    0.0      0.0   0.0   0.0       0.0         0.0       0.0
25   0.0    0.0    0.0      0.0   0.0   0.0       0.0         0.0       0.0
28   0.0    0.0    0.0      0.0   0.0   0.0       0.0         0.0       0.0

    adiant  ador  ador produt  adquir  adquir consegu  adquir produt  adult  \
14     0.0   0.0          0.0     0.0             0.0            0.0    0.0
23     0.0   0.0          0.0     0.0             0.0            0.0    0.0
24     0.0   0.0          0.0     0.0             0.0            0.0    0.0
25     0.0   0.0          0.0     0.0             0.0            0.0    0.0
28     0.0   0.0          0.0     0.0             0.0            0.0    0.0

    afet  afet ades  aff  afff  afi  afinal  afirm   ag  agenc  agenc correi  \
14   0.0        0.0  0.0   0.0  0.0     0.0    0.0  0.0    0.0           0.0
23   0.0        0.0  0.0   0.0  0.0     0.0    0.0  0.0    0.0           0.0
24   0.0        0.0  0.0   0.0  0.0     0.0    0.0  0.0    0.0           0.0
25   0.0        0.0  0.0   0.0  0.0     0.0    0.0  0.0    0.0           0.0
28   0.0        0.0  0.0   0.0  0.0     0.0    0.0  0.0    0.0           0.0

    agil  agiliz      agor  agor aguard  agor cheg  agor consegu  agor entr  \
14   0.0     0.0  0.000000          0.0        0.0           0.0        0.0
23   0.0     0.0  0.240835          0.0        0.0           0.0        0.0
24   0.0     0.0  0.000000          0.0        0.0           0.0        0.0
25   0.0     0.0  0.000000          0.0        0.0           0.0        0.0
28   0.0     0.0  0.000000          0.0        0.0           0.0        0.0

    agor esper  agor faz  agor faç  agor ja  agor nad  agor nao  agor nenhum  \
14         0.0       0.0  0.000000      0.0       0.0       0.0          0.0
23         0.0       0.0  0.452191      0.0       0.0       0.0          0.0
24         0.0       0.0  0.000000      0.0       0.0       0.0          0.0
25         0.0       0.0  0.000000      0.0       0.0       0.0          0.0
28         0.0       0.0  0.000000      0.0       0.0       0.0          0.0

    agor ninguém  agor obtiv  agor produt  agor receb  agor resolv  \
14           0.0         0.0          0.0         0.0          0.0
23           0.0         0.0          0.0         0.0          0.0
24           0.0         0.0          0.0         0.0          0.0
25           0.0         0.0          0.0         0.0          0.0
28           0.0         0.0          0.0         0.0          0.0

    agor respost  agor retorn  agor vou  agrad  agradeç  aguard  aguard aind  \
14           0.0          0.0       0.0    0.0      0.0     0.0          0.0
23           0.0          0.0       0.0    0.0      0.0     0.0          0.0
24           0.0          0.0       0.0    0.0      0.0     0.0          0.0
25           0.0          0.0       0.0    0.0      0.0     0.0          0.0
28           0.0          0.0       0.0    0.0      0.0     0.0          0.0

    aguard contat  aguard entreg  aguard envi  aguard orient  aguard outr  \
14            0.0            0.0          0.0            0.0          0.0
23            0.0            0.0          0.0            0.0          0.0
24            0.0            0.0          0.0            0.0          0.0
25            0.0            0.0          0.0            0.0          0.0
28            0.0            0.0          0.0            0.0          0.0

    aguard pos  aguard posicion  aguard produt  aguard provid  aguard receb  \
14         0.0              0.0            0.0            0.0           0.0
23         0.0              0.0            0.0            0.0           0.0
24         0.0              0.0            0.0            0.0           0.0
25         0.0              0.0            0.0            0.0           0.0
28         0.0              0.0            0.0            0.0           0.0

    aguard resoluç  aguard respost  aguard rest  aguard retorn  aguard segund  \
14             0.0             0.0          0.0            0.0            0.0
23             0.0             0.0          0.0            0.0            0.0
24             0.0             0.0          0.0            0.0            0.0
25             0.0             0.0          0.0            0.0            0.0
28             0.0             0.0          0.0            0.0            0.0

    aguard soluç  aguard troc  agênc  agênc correi   ai  aind  aind aguard  \
14           0.0          0.0    0.0           0.0  0.0   0.0          0.0
23           0.0          0.0    0.0           0.0  0.0   0.0          0.0
24           0.0          0.0    0.0           0.0  0.0   0.0          0.0
25           0.0          0.0    0.0           0.0  0.0   0.0          0.0
28           0.0          0.0    0.0           0.0  0.0   0.0          0.0

    aind assim  aind bem  aind cheg  aind cim  aind consegu  aind constrang  \
14         0.0       0.0        0.0       0.0           0.0             0.0
23         0.0       0.0        0.0       0.0           0.0             0.0
24         0.0       0.0        0.0       0.0           0.0             0.0
25         0.0       0.0        0.0       0.0           0.0             0.0
28         0.0       0.0        0.0       0.0           0.0             0.0

    aind dentr  aind entreg  aind esper  aind falt  aind instal  aind mand  \
14         0.0          0.0         0.0        0.0          0.0        0.0
23         0.0          0.0         0.0        0.0          0.0        0.0
24         0.0          0.0         0.0        0.0          0.0        0.0
25         0.0          0.0         0.0        0.0          0.0        0.0
28         0.0          0.0         0.0        0.0          0.0        0.0

    aind nao  aind obtiv  aind poss  aind praz  aind produt  aind receb  \
14       0.0         0.0        0.0        0.0          0.0         0.0
23       0.0         0.0        0.0        0.0          0.0         0.0
24       0.0         0.0        0.0        0.0          0.0         0.0
25       0.0         0.0        0.0        0.0          0.0         0.0
28       0.0         0.0        0.0        0.0          0.0         0.0

    aind respost  aind retorn  aind test  aind use  aind vei  aind vou  ajud  \
14           0.0          0.0        0.0       0.0       0.0       0.0   0.0
23           0.0          0.0        0.0       0.0       0.0       0.0   0.0
24           0.0          0.0        0.0       0.0       0.0       0.0   0.0
25           0.0          0.0        0.0       0.0       0.0       0.0   0.0
28           0.0          0.0        0.0       0.0       0.0       0.0   0.0

    ajust  aleg  alem  alem diss  alg  algod  algod vei  algu  algum  \
14    0.0   0.0   0.0        0.0  0.0    0.0        0.0   0.0    0.0
23    0.0   0.0   0.0        0.0  0.0    0.0        0.0   0.0    0.0
24    0.0   0.0   0.0        0.0  0.0    0.0        0.0   0.0    0.0
25    0.0   0.0   0.0        0.0  0.0    0.0        0.0   0.0    0.0
28    0.0   0.0   0.0        0.0  0.0    0.0        0.0   0.0    0.0

    algum cois  algum part  algum peç  algum pincel  algum problem  \
14         0.0         0.0        0.0           0.0            0.0
23         0.0         0.0        0.0           0.0            0.0
24         0.0         0.0        0.0           0.0            0.0
25         0.0         0.0        0.0           0.0            0.0
28         0.0         0.0        0.0           0.0            0.0

    algum produt  alguém  ali  alicat  aliás  almof  alt  alter  altern  \
14           0.0     0.0  0.0     0.0    0.0    0.0  0.0    0.0     0.0
23           0.0     0.0  0.0     0.0    0.0    0.0  0.0    0.0     0.0
24           0.0     0.0  0.0     0.0    0.0    0.0  0.0    0.0     0.0
25           0.0     0.0  0.0     0.0    0.0    0.0  0.0    0.0     0.0
28           0.0     0.0  0.0     0.0    0.0    0.0  0.0    0.0     0.0

    altur  alumíni  alç  além  além diss  além pag  além produt  além ter  \
14    0.0      0.0  0.0   0.0        0.0       0.0          0.0       0.0
23    0.0      0.0  0.0   0.0        0.0       0.0          0.0       0.0
24    0.0      0.0  0.0   0.0        0.0       0.0          0.0       0.0
25    0.0      0.0  0.0   0.0        0.0       0.0          0.0       0.0
28    0.0      0.0  0.0   0.0        0.0       0.0          0.0       0.0

    além vir   am  amanhã  amarel  amass  ambi  ambos  ame  americ  amig  \
14       0.0  0.0     0.0     0.0    0.0   0.0    0.0  0.0     0.0   0.0
23       0.0  0.0     0.0     0.0    0.0   0.0    0.0  0.0     0.0   0.0
24       0.0  0.0     0.0     0.0    0.0   0.0    0.0  0.0     0.0   0.0
25       0.0  0.0     0.0     0.0    0.0   0.0    0.0  0.0     0.0   0.0
28       0.0  0.0     0.0     0.0    0.0   0.0    0.0  0.0     0.0   0.0

    amér  and  aniversári  ano  ano nunc  ant  ant compr  ant dat  ant envi  \
14   0.0  0.0         0.0  0.0       0.0  0.0        0.0      0.0       0.0
23   0.0  0.0         0.0  0.0       0.0  0.0        0.0      0.0       0.0
24   0.0  0.0         0.0  0.0       0.0  0.0        0.0      0.0       0.0
25   0.0  0.0         0.0  0.0       0.0  0.0        0.0      0.0       0.0
28   0.0  0.0         0.0  0.0       0.0  0.0        0.0      0.0       0.0

    ant praz  ant previst  antecip  anten  anteri  antig  anunc  anunci  \
14       0.0          0.0      0.0    0.0     0.0    0.0    0.0     0.0
23       0.0          0.0      0.0    0.0     0.0    0.0    0.0     0.0
24       0.0          0.0      0.0    0.0     0.0    0.0    0.0     0.0
25       0.0          0.0      0.0    0.0     0.0    0.0    0.0     0.0
28       0.0          0.0      0.0    0.0     0.0    0.0    0.0     0.0

    anunci diz  anunci fot  anunci nao  anunci produt  anunci vei    anúnci  \
14         0.0         0.0         0.0            0.0         0.0  0.000000
23         0.0         0.0         0.0            0.0         0.0  0.000000
24         0.0         0.0         0.0            0.0         0.0  0.278037
25         0.0         0.0         0.0            0.0         0.0  0.000000
28         0.0         0.0         0.0            0.0         0.0  0.000000

    anúnci diz  anúnci quer  aond  apag  apar  apar us  aparec  aparec fot  \
14         0.0          0.0   0.0   0.0   0.0      0.0     0.0         0.0
23         0.0          0.0   0.0   0.0   0.0      0.0     0.0         0.0
24         0.0          0.0   0.0   0.0   0.0      0.0     0.0         0.0
25         0.0          0.0   0.0   0.0   0.0      0.0     0.0         0.0
28         0.0          0.0   0.0   0.0   0.0      0.0     0.0         0.0

    aparec sit  aparelh  aparelh celul  aparelh func  aparent  apart  apen  \
14         0.0      0.0            0.0           0.0      0.0    0.0   0.0
23         0.0      0.0            0.0           0.0      0.0    0.0   0.0
24         0.0      0.0            0.0           0.0      0.0    0.0   0.0
25         0.0      0.0            0.0           0.0      0.0    0.0   0.0
28         0.0      0.0            0.0           0.0      0.0    0.0   0.0

    apen aguard  apen cade  apen caix  apen cap  apen cartuch  apen cas  \
14          0.0        0.0        0.0       0.0           0.0       0.0
23          0.0        0.0        0.0       0.0           0.0       0.0
24          0.0        0.0        0.0       0.0           0.0       0.0
25          0.0        0.0        0.0       0.0           0.0       0.0
28          0.0        0.0        0.0       0.0           0.0       0.0

    apen cheg  apen compr  apen doi  apen dua  apen entreg  apen falt  \
14        0.0         0.0       0.0       0.0          0.0        0.0
23        0.0         0.0       0.0       0.0          0.0        0.0
24        0.0         0.0       0.0       0.0          0.0        0.0
25        0.0         0.0       0.0       0.0          0.0        0.0
28        0.0         0.0       0.0       0.0          0.0        0.0

    apen frágil  apen gost  apen it  apen jog  apen kit  apen luminár  \
14          0.0        0.0      0.0       0.0       0.0           0.0
23          0.0        0.0      0.0       0.0       0.0           0.0
24          0.0        0.0      0.0       0.0       0.0           0.0
25          0.0        0.0      0.0       0.0       0.0           0.0
28          0.0        0.0      0.0       0.0       0.0           0.0

    apen metad  apen not  apen pacot  apen papel  apen pra  apen produt  \
14         0.0       0.0         0.0         0.0       0.0          0.0
23         0.0       0.0         0.0         0.0       0.0          0.0
24         0.0       0.0         0.0         0.0       0.0          0.0
25         0.0       0.0         0.0         0.0       0.0          0.0
28         0.0       0.0         0.0         0.0       0.0          0.0

    apen quer  apen receb  apen send  apen tent  apen unidad  apert  apes  \
14        0.0         0.0        0.0        0.0          0.0    0.0   0.0
23        0.0         0.0        0.0        0.0          0.0    0.0   0.0
24        0.0         0.0        0.0        0.0          0.0    0.0   0.0
25        0.0         0.0        0.0        0.0          0.0    0.0   0.0
28        0.0         0.0        0.0        0.0          0.0    0.0   0.0

    apes const  apes dentr  apes entreg  apes produt  apes ter  aplic  apo  \
14         0.0         0.0          0.0          0.0       0.0    0.0  0.0
23         0.0         0.0          0.0          0.0       0.0    0.0  0.0
24         0.0         0.0          0.0          0.0       0.0    0.0  0.0
25         0.0         0.0          0.0          0.0       0.0    0.0  0.0
28         0.0         0.0          0.0          0.0       0.0    0.0  0.0

    apoi  app  appl  apresent  apresent defeit  apresent fot  \
14   0.0  0.0   0.0       0.0              0.0           0.0
23   0.0  0.0   0.0       0.0              0.0           0.0
24   0.0  0.0   0.0       0.0              0.0           0.0
25   0.0  0.0   0.0       0.0              0.0           0.0
28   0.0  0.0   0.0       0.0              0.0           0.0

    apresent problem  apresent produt  apresent sit  aprov  após  após compr  \
14               0.0              0.0           0.0    0.0   0.0         0.0
23               0.0              0.0           0.0    0.0   0.0         0.0
24               0.0              0.0           0.0    0.0   0.0         0.0
25               0.0              0.0           0.0    0.0   0.0         0.0
28               0.0              0.0           0.0    0.0   0.0         0.0

    após efetu  após praz  após receb  aqu  aquec  aquis  aquém       ar  \
14         0.0        0.0         0.0  0.0    0.0    0.0    0.0  0.30022
23         0.0        0.0         0.0  0.0    0.0    0.0    0.0  0.00000
24         0.0        0.0         0.0  0.0    0.0    0.0    0.0  0.00000
25         0.0        0.0         0.0  0.0    0.0    0.0    0.0  0.00000
28         0.0        0.0         0.0  0.0    0.0    0.0    0.0  0.00000

    ar condicion  aranh  arar  arar roup  arm  armazen  aro  arranh  arrepend  \
14      0.316521    0.0   0.0        0.0  0.0      0.0  0.0     0.0       0.0
23      0.000000    0.0   0.0        0.0  0.0      0.0  0.0     0.0       0.0
24      0.000000    0.0   0.0        0.0  0.0      0.0  0.0     0.0       0.0
25      0.000000    0.0   0.0        0.0  0.0      0.0  0.0     0.0       0.0
28      0.000000    0.0   0.0        0.0  0.0      0.0  0.0     0.0       0.0

    arrepend compr  arrum  aspect  aspect queim  aspir  assent  assim  \
14             0.0    0.0     0.0           0.0    0.0     0.0    0.0
23             0.0    0.0     0.0           0.0    0.0     0.0    0.0
24             0.0    0.0     0.0           0.0    0.0     0.0    0.0
25             0.0    0.0     0.0           0.0    0.0     0.0    0.0

### (3.3) LDA

🕵🏻‍♂️ Fit LDA:
- Choose `n_components = 3`
- Show the Document-Topic Mixture with *.transform()*
- Show the Topic Mixture with *.components_*

In [18]:
n_components = 3
lda = LatentDirichletAllocation(n_components=n_components, random_state=42)
lda.fit(vectorized_reviews)

LatentDirichletAllocation(n_components=3, random_state=42)

#### Document Mixture (for Topics)

In [19]:
document_mixture = lda.transform(vectorized_reviews)
document_mixture

array([[0.07862797, 0.07843889, 0.84293314],
       [0.08294103, 0.08119877, 0.8358602 ],
       [0.08501857, 0.83717411, 0.07780732],
       ...,
       [0.15426997, 0.06646051, 0.77926951],
       [0.08864652, 0.09629065, 0.81506284],
       [0.81132625, 0.09709636, 0.0915774 ]])

👉 Let's report the most important topic for each review

In [23]:
most_important_topic = document_mixture.argmax(axis=1)
df.loc[bad_reviews_df.index, "most_important_topic"] = most_important_topic
most_important_topic

array([2, 2, 1, ..., 2, 2, 0])

#### Topic Mixture (for Words)

In [24]:
topic_word_mixture = lda.components_
topic_word_mixture

array([[ 1.4471101 ,  1.3027199 ,  2.68372512, ...,  0.33418771,
         1.25739753,  3.42847017],
       [ 3.22038338, 12.40199582,  0.36484821, ...,  1.42603701,
         2.06968493,  0.37297657],
       [ 0.34170859,  0.34474853,  0.35062439, ...,  0.33910428,
         0.43384833,  0.34205418]])

#### Topics

🎁 We provide some helper functions:
- `topic_word`: returns the most important words and their weights for a single topic
- `print_topics`: prints the different topics found by LDA with their most important words

In [25]:
def topic_word(vectorizer, model, topic, topwords, with_weights = True):
    topwords_indexes = topic.argsort()[:-topwords - 1:-1]
    if with_weights == True:
        topwords = [(vectorizer.get_feature_names_out()[i], round(topic[i],2)) for i in topwords_indexes]
    if with_weights == False:
        topwords = [vectorizer.get_feature_names_out()[i] for i in topwords_indexes]
    return topwords

In [26]:
def print_topics(vectorizer, model, topwords):
    for idx, topic in enumerate(model.components_):
        print("-"*20)
        print("Topic %d:" % (idx))
        print(topic_word(vectorizer, model, topic, topwords))

🕵🏻‍♂️ Print the topics with the most commonly used words:

In [34]:
print_topics(vectorizer, lda, 10)

--------------------
Topic 0:
[('produt', 201.36), ('receb', 186.07), ('vei', 139.23), ('receb produt', 133.17), ('gost', 106.32), ('nao', 106.06), ('compr', 105.45), ('err', 91.42), ('defeit', 87.82), ('difer', 75.59)]
--------------------
Topic 1:
[('bom', 230.0), ('produt', 227.43), ('entreg', 130.77), ('praz', 120.07), ('qual', 113.3), ('recom', 103.35), ('vei', 71.83), ('cheg', 70.56), ('bem', 66.11), ('péss', 60.98)]
--------------------
Topic 2:
[('entreg', 176.74), ('receb', 165.73), ('compr', 151.92), ('falt', 113.57), ('ped', 109.78), ('apen', 107.26), ('cheg', 106.1), ('produt', 93.56), ('doi', 89.12), ('aguard', 85.89)]

🇧🇷 Burada biraz Brezilya Portekizcesi kelimeler var:
- _cadeiras = chairs_
- _produto = product_
- _recomendo = recommend (não recomendo == not recommend)_
- _bom = good_
- _comprei = bought_
- _veio = came_
- _errado = wrong_
- _gostaria = I would like to..._
- _duas = two_
- _nao = not_
- _entregue = delivered_
- _pecas = part_
- _ainda = yet_
- _recebi = received_

👉 Show the most popular words associated with a topic

In [28]:
topic_word_mixture = [
    topic_word(vectorizer, lda, topic, topwords=10, with_weights=False)
    for topic in lda.components_
]

In [30]:
df["most_important_words"] = df["most_important_topic"].apply(
    lambda i: topic_word_mixture[int(i)] if pd.notna(i) else None
)

In [31]:
df[["review_id",
        "review_score",
        "product_category_name",
        "full_review_cleaned",
        "most_important_topic",
        "most_important_words"]
      ].head()

,review_id,review_score,product_category_name,full_review_cleaned,most_important_topic,most_important_words
0,e64fb393e7b32834bb789ff8bb30750e,5,ferramentas_jardim,receb bem ant praz estipul,NaN,None
1,f7c4243c7fe1938f181bec41a392bdeb,5,esporte_lazer,parabém loj lannist ador compr internet segur ...,NaN,None
2,8670d52e15e00043ae7de4c01cc2fe06,4,eletroportateis,recom aparelh efici sit marc aparelh impress d...,NaN,None
3,4b49719c8a200003f700d3d986ea1a19,4,beleza_saude,pouc travandopel val ta boa,NaN,None
4,3948b09f7c818e2d86c9a546758b2335,5,informatica_acessorios,sup recom vend confi produt ok entreg ant praz,NaN,None

In [35]:
df[df.review_score < 4][["review_id",
    "review_score",
    "product_category_name",
    "full_review_cleaned",
    "most_important_topic",
    "most_important_words"]
].head()

,review_id,review_score,product_category_name,full_review_cleaned,most_important_topic,most_important_words
14,e233e51d11511bf30e568c76360ace52,1,eletronicos,receb soment control mide split estil falt con...,2.0,"[entreg, receb, compr, falt, ped, apen, cheg, ..."
23,8b230a1373c6dc4bd867099fda1d7039,3,ferramentas_jardim,compr dua unidad receb agor faç,2.0,"[entreg, receb, compr, falt, ped, apen, cheg, ..."
24,cb2fc3e5711b5ae85e0491ee18af63ed,3,beleza_saude,produt bom porém vei mim condiz fot anúnci,1.0,"[bom, produt, entreg, praz, qual, recom, vei, ..."
25,60c714ed14cef913944a3147094a4742,1,moveis_decoracao,produt inferi mal acab,1.0,"[bom, produt, entreg, praz, qual, recom, vei, ..."
28,0bd4dcc4f6c4621baf37f73495cad8c4,3,esporte_lazer,entreg praz,1.0,"[bom, produt, entreg, praz, qual, recom, vei, ..."

## (3.4) Pipeline Tf-Idf and LDA

In [33]:
from sklearn import set_config
set_config("diagram")

🔨 Create a Pipeline connecting the previous Vectorizer and LDA.

Fit it on the cleaned texts.

In [39]:
pipeline = make_pipeline(
    TfidfVectorizer(ngram_range=(1, 2), max_df=0.75, max_features=5000),
    LatentDirichletAllocation(n_components=3, random_state=42)
)
pipeline.fit(bad_reviews_df["full_review_cleaned"])

Pipeline(steps=[('tfidfvectorizer',
                 TfidfVectorizer(max_df=0.75, max_features=5000,
                                 ngram_range=(1, 2))),
                ('latentdirichletallocation',
                 LatentDirichletAllocation(n_components=3, random_state=42))])

💡 If you try to access the components via `pipeline.components_`, it will NOT work because Pipeline does not have `components_`. However, you can use `pipeline._final_estimator` to access the LDA. And from there you can access the topics!

In [40]:
pipeline._final_estimator

LatentDirichletAllocation(n_components=3, random_state=42)

In [41]:
pipeline._final_estimator.components_

array([[ 1.4471101 ,  1.3027199 ,  2.68372512, ...,  0.33418771,
         1.25739753,  3.42847017],
       [ 3.22038338, 12.40199582,  0.36484821, ...,  1.42603701,
         2.06968493,  0.37297657],
       [ 0.34170859,  0.34474853,  0.35062439, ...,  0.33910428,
         0.43384833,  0.34205418]])

**Document Mixture** with Pipeline:

In [42]:
document_mixture = pipeline.transform(bad_reviews_df["full_review_cleaned"])
document_mixture

array([[0.07862797, 0.07843889, 0.84293314],
       [0.08294103, 0.08119877, 0.8358602 ],
       [0.08501857, 0.83717411, 0.07780732],
       ...,
       [0.15426997, 0.06646051, 0.77926951],
       [0.08864652, 0.09629065, 0.81506284],
       [0.81132625, 0.09709636, 0.0915774 ]])

**Topic Mixture** with Pipeline:

In [43]:
topic_mixture = pipeline._final_estimator.components_
topic_mixture

array([[ 1.4471101 ,  1.3027199 ,  2.68372512, ...,  0.33418771,
         1.25739753,  3.42847017],
       [ 3.22038338, 12.40199582,  0.36484821, ...,  1.42603701,
         2.06968493,  0.37297657],
       [ 0.34170859,  0.34474853,  0.35062439, ...,  0.33910428,
         0.43384833,  0.34205418]])

## (4) 🎁 Product Categories

### (4.1) Grouping by product categories

📈 Group the dataset by `product_category_name` and examine their performance.

In [44]:
# Product categories by performance - look at count, mean, median, and standard deviation
product_categories = df.groupby(by = 'product_category_name').agg({
        'review_score': ["count", "mean", "median", "std"]
    })

# Remove products with fewer sales than a threshold for analysis
cutoff = 50
product_categories = product_categories[product_categories[("review_score", "count")] > cutoff]

# Sort product categories by performance
product_categories = product_categories.sort_values(by = [('review_score', 'mean'),
                                                          ('review_score', 'std')],
                                                    ascending = [False, True])
product_categories

                                               review_score                   \
                                                      count      mean median
product_category_name
alimentos_bebidas                                        75  4.560000    5.0
livros_interesse_geral                                  152  4.539474    5.0
malas_acessorios                                        375  4.317333    5.0
livros_tecnicos                                          83  4.301205    5.0
pcs                                                      67  4.283582    5.0
alimentos                                               151  4.231788    5.0
papelaria                                               758  4.201847    5.0
instrumentos_musicais                                   228  4.192982    5.0
fashion_calcados                                        101  4.188119    5.0
fashion_bolsas_e_acessorios                             726  4.168044    5.0
perfumaria                                             1094  4.167276    5.0
construcao_ferramentas_jardim                            85  4.164706    5.0
cool_stuff                                             1360  4.154412    5.0
ferramentas_jardim                                     1391  4.105679    5.0
beleza_saude                                           3046  4.104071    5.0
brinquedos                                             1271  4.101495    5.0
esporte_lazer                                          2637  4.097838    5.0
bebidas                                                 111  4.090090    5.0
pet_shop                                                603  4.086235    5.0
construcao_ferramentas_iluminacao                        86  4.081395    5.0
eletroportateis                                         242  4.061983    5.0
automotivo                                             1533  4.049576    5.0
eletrodomesticos                                        354  4.033898    5.0
eletrodomesticos_2                                       89  4.011236    5.0
relogios_presentes                                     2211  4.009950    5.0
construcao_ferramentas_construcao                       277  4.007220    5.0
consoles_games                                          339  4.005900    5.0
utilidades_domesticas                                  2192  4.005018    5.0
eletronicos                                             942  3.979830    5.0
industria_comercio_e_negocios                            82  3.963415    5.0
bebes                                                   882  3.955782    5.0
sinalizacao_e_seguranca                                  61  3.934426    5.0
telefonia                                              1654  3.874244    5.0
cama_mesa_banho                                        3891  3.853765    5.0
artes                                                    80  3.850000    5.0
casa_conforto                                           175  3.817143    5.0
moveis_decoracao                                       2311  3.815232    5.0
moveis_sala                                             138  3.789855    5.0
informatica_acessorios                                 2473  3.774767    5.0
audio                                                   134  3.768657    5.0
market_place                                            102  3.745098    4.0
moveis_cozinha_area_de_servico_jantar_e_jardim           94  3.734043    4.0
construcao_ferramentas_seguranca                         61  3.721311    5.0
agro_industria_e_comercio                                57  3.701754    4.0
telefonia_fixa                                           96  3.697917    4.0
casa_construcao                                         177  3.672316    4.0
climatizacao                                             93  3.655914    4.0
fashion_roupa_masculina                                  56  3.482143    4.0
moveis_escritorio                                       546  3.298535    4.0


                                                     std
product_category_name
alimentos_bebidas                               0.873638
livros_interesse_geral                          1.060311
malas_acessorios                                1.225004
livros_tecnicos                                 1.294783
pcs                                             1.300419
alimentos                                       1.308657
papelaria                                       1.281984
instrumentos_musicais                           1.247921
fashion_calcados                                1.369035
fashion_bolsas_e_acessorios                     1.287338
perfumaria                                      1.381616
construcao_ferramentas_jardim                   1.421326
cool_stuff                                      1.324355
ferramentas_jardim                              1.367523
beleza_saude                                    1.375126
brinquedos                                      1.393999
esporte_lazer                                   1.375699
bebidas                                         1.391857
pet_shop                                        1.383046
construcao_ferramentas_iluminacao               1.294469
eletroportateis                                 1.457660
automotivo                                      1.403146
eletrodomesticos                                1.453328
eletrodomesticos_2                              1.327116
relogios_presentes                              1.410334
construcao_ferramentas_construcao               1.432017
consoles_games                                  1.388870
utilidades_domesticas                           1.404327
eletronicos                                     1.439025
industria_comercio_e_negocios                   1.418094
bebes                                           1.461296
sinalizacao_e_seguranca                         1.459096
telefonia                                       1.462134
cama_mesa_banho                                 1.484954
artes                                           1.493446
casa_conforto                                   1.508879
moveis_decoracao                                1.515019
moveis_sala                                     1.511286
informatica_acessorios                          1.548246
audio                                           1.574774
market_place                                    1.480475
moveis_cozinha_area_de_servico_jantar_e_jardim  1.496775
construcao_ferramentas_seguranca                1.654601
agro_industria_e_comercio                       1.463422
telefonia_fixa                                  1.576938
casa_construcao                                 1.498094
climatizacao                                    1.625173
fashion_roupa_masculina                         1.737198
moveis_escritorio                               1.562366

### (4.2) Worst product categories

👎 Save the five worst categories in terms of *average review score* into a variable called `worst_products`.

In [45]:
worst_products = product_categories.tail(5).sort_values(by = [("review_score", "count")],
                                                       ascending = False)
worst_products

                        review_score
                               count      mean median       std
product_category_name
moveis_escritorio                546  3.298535    4.0  1.562366
casa_construcao                  177  3.672316    4.0  1.498094
telefonia_fixa                    96  3.697917    4.0  1.576938
climatizacao                      93  3.655914    4.0  1.625173
fashion_roupa_masculina           56  3.482143    4.0  1.737198

👇 Create a `worst_products_reviews` DataFrame containing only the items in `worst_products`.

In [46]:
worst_products_reviews = df[df.product_category_name.isin(worst_products.index)]
worst_products_reviews[["review_id",
                        "review_score",
                        "product_category_name",
                        "full_review_cleaned",
                        "most_important_topic",
                        "most_important_words"]
      ]

,review_id,review_score,product_category_name,full_review_cleaned,most_important_topic,most_important_words
45,c422274e50e900b46fee429016c5458d,3,moveis_escritorio,gost,0.0,"[produt, receb, vei, receb produt, gost, nao, ..."
126,5d6f9cddc8335878d8bf20c3bd4602e8,5,moveis_escritorio,meg recom receb produt corret dentr prazoverif...,NaN,None
212,1f836d160f50247a394034abd93b7c24,3,casa_construcao,esper instal,1.0,"[bom, produt, entreg, praz, qual, recom, vei, ..."
219,edd86e0af4dc62b340c60d846643cbf9,5,moveis_escritorio,produt ok praz estendidoporém entreg praz divu...,NaN,None
232,e47020cf52099bce9dc57524ea41218b,4,moveis_escritorio,indic loj compr sempr lannist,NaN,None
...,...,...,...,...,...,...
35956,123381026f13c723cb967b14b1bc673a,5,moveis_escritorio,ador cade bonit confort fácil mont mesm mont o...,NaN,None
36031,042b7c995635364a03c5bb79e994f513,4,fashion_roupa_masculina,filh gost,NaN,None
36034,5d4beea8e2c71baee7f55c7ae3ae3313,1,moveis_escritorio,insatisfeit cade vei defeit fabr solt encaix p...,0.0,"[produt, receb, vei, receb produt, gost, nao, ..."
36037,0cac8fef1bcba2a3335b132807520f6d,1,moveis_escritorio,produt vei fur err mont infeliz cade vai dur m...,1.0,"[bom, produt, entreg, praz, qual, recom, vei, ..."
36098,dfb01be03c8f304bb01e3d2d90719a5b,1,casa_construcao,ped dand entreg receb luminár,2.0,"[entreg, receb, compr, falt, ped, apen, cheg, ..."

### (4.3) Topics for the worst products

❓ What are the topics of the worst products? ❓

In [47]:
worst_products_reviews["most_important_topic"].value_counts()

most_important_topic
2.0    160
1.0    148
0.0    106
Name: count, dtype: int64

In [48]:
bad_frequency = list(worst_products_reviews["most_important_topic"].value_counts().index)
bad_frequency

[2.0, 1.0, 0.0]

In [51]:
[topic_word_mixture[int(i)] for i in bad_frequency]

[['entreg',
  'receb',
  'compr',
  'falt',
  'ped',
  'apen',
  'cheg',
  'produt',
  'doi',
  'aguard'],
 ['bom',
  'produt',
  'entreg',
  'praz',
  'qual',
  'recom',
  'vei',
  'cheg',
  'bem',
  'péss'],
 ['produt',
  'receb',
  'vei',
  'receb produt',
  'gost',
  'nao',
  'compr',
  'err',
  'defeit',
  'difer']]

## (5) 🎁 Sellers...

* What kind of products were sold by the worst sellers?
* What are the main reviews for the worst sellers?

### (5.1) Worst sellers

In [ ]:
from olist.seller import Seller
sellers = Seller().get_training_data()
sellers.columns

👇 Select the 10 worst-selling sellers and save them into a variable called `worst_sellers`.

In [ ]:
worst_sellers = sellers[["seller_id", "review_score", "profits"]].sort_values(
    by = "profits",
    ascending = True).head(10)
worst_sellers

### (5.2) Products sold by the worst sellers

In [ ]:
products = Product().get_training_data() [["product_id", "category"]]
products

❓ What types of products are sold by the worst sellers? ❓

In [ ]:
sellers_product_category = data["order_items"].merge(products,
                                             on = "product_id", how = "left")[["seller_id", "category"]]

sellers_product_category

In [ ]:
sellers_product_category.groupby("seller_id").count()

### (5.3) Categories and topics for the worst sellers

🎁 Here are some useful functions:
- `focus_seller(seller_id)` to show product categories sold by a seller
- `bad_reviews_seller` to show the most popular words of the most frequent topics for a seller

In [ ]:
def focus_seller(seller_id):
    return sellers_product_category[sellers_product_category.seller_id == seller_id].value_counts()

In [ ]:
bad_reviews_sellers = worst_products_reviews.merge(data["order_items"])
bad_reviews_sellers.head(3)

In [ ]:
def bad_reviews_seller(bad_reviews_sellers, seller_id):
    mask = (bad_reviews_sellers.seller_id == seller_id)
    temp = bad_reviews_sellers[mask]
    if len(temp) > 0: # if seller appears in the bad reviews dataframe
        most_frequent_topic_seller = list(temp.most_important_topic.value_counts().head(1).index)[0]
        return topic_word_mixture[most_frequent_topic_seller]

❓ For each of these worst-selling sellers, show the most frequent product categories and words ❓

In [ ]:
for worst_seller in worst_sellers["seller_id"]:
    print("-"*50)
    print(f"Focusing on the seller #{worst_seller}...")
    print(focus_seller(worst_seller))
    print(bad_reviews_seller(bad_reviews_sellers, worst_seller))

🏁 Congratulations. You have learned some NLP basics (Preprocessing + Vectorization + NB/LDA) and combined this new "expertise" with Decision Science.

💾 Do not forget to `git add / commit / push`.